version: '3.8'

services:
  api-donation:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_H2_CONSOLE_ENABLED: "true"
      JAVA_HOME: /usr/local/openjdk-11
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2
    ports:
      - "9092:8082"